name: example
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  map_model: ^1.0.3

dev_dependencies:
  build_runner: ^2.4.4
  map_model_builder: ^1.0.3
  lints: ^2.0.0
  test: ^1.21.0
