name: map_model

description: MapModel as its name suggests. Implement various Model objects using Map, such as Entity, VO, and DTO.

homepage: 'https://github.com/ellisez/MapModel'

version: 1.0.3

environment:
  sdk: '>=2.19.6 <4.0.0'


