builders:
  map_model_builder:
    import: 'package:map_model_builder/builder.dart'
    builder_factories: ['mapModelBuilder']
    build_extensions: { ".dart": [ ".g.part" ] }
    auto_apply: root_package
    build_to: source