name: map_model_builder

description: MapModel as its name suggests. Implement various Model objects using Map, such as Entity, VO, and DTO.

publish_to: 'https://github.com/ellisez/MapModel'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  source_gen: ^1.3.2
  analyzer: ^5.12.0
  map_model: any

dev_dependencies:
  build_test: any
  build_web_compilers: any
