name: map_model_builder

description: MapModel as its name suggests. Implement various Model objects using Map, such as Entity, VO, and DTO.

homepage: 'https://github.com/ellisez/MapModel'

version: 1.0.7

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  build: ^2.4.0
  build_runner: ^2.4.4
  source_gen: ^1.3.2
  analyzer: ^5.12.0
  map_model: ^1.0.3

dev_dependencies:
  build_test: any
  build_web_compilers: any
